from LookupTables.permittivity_lookup import permittivity_lookup
from LookupTables.permittivity_lookup import VALID_MATERIALS, MIN_FREQUENCY, MAX_FREQUENCY
from LookupTables.permittivity_lookup import PERMEABILITY_OF_FREE_SPACE, PERMITTIVITY_OF_FREE_SPACE
from LookupTables.permittivity_lookup import IMPEDANCE_OF_FREE_SPACE, INV_IMPEDANCE_OF_FREE_SPACE
from LookupTables.permittivity_lookup import SPEED_OF_LIGHT_VACUUM
